package com.example.BookStoreApiPractice.domain.entites.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder

@Table (name = "books")
@Entity
public class BookEntity {
    @Id
    private String isbn;// isbn is generated by us

    private String bookName;

    private String yearPublished;

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "author_id")
    private AuthorEntity author;
}
