package com.example.BookStoreApiPractice.domain.entites.dto;


import com.example.BookStoreApiPractice.domain.entites.entity.AuthorEntity;
import jakarta.persistence.CascadeType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;

@NoArgsConstructor
@AllArgsConstructor
@Data
public class BookDto {
    private String isbn;// isbn is generated by us

    private String bookName;

    private String yearPublished;

    private Long AuthorId;
}
